/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import React, { useRef , useState} from "react";
import { useGLTF } from "@react-three/drei";
import { useThree,useFrame  } from "@react-three/fiber";
import islandScene from "../assets/3d/island.glb";
import mayanIsland from "../assets/3d/dae_islands_mayan_pottery.glb";
import {a} from "@react-spring/three";

const Island = ({isRotating, setIsRotating ,setCurrentStage, ...props}) =>{
    
    const islandRef = useRef();
    const {gl,viewport} = useThree();
    const lastX = useRef(0);
    const rotationSpeed =  useRef(0)
    const dampingFactor = 0.95;
//   const { nodes, materials } = useGLTF(islandScene);
    const {nodes, materials} = useGLTF(mayanIsland);


  const handlePointerDown = (e)=>{
    e.stopPropagation();
    e.preventDefault()
    setIsRotating(true);

    //we need to check once we press the pointer down if it is a touch event, a press event or a mouse event
    const clientX = e.touches ? e.touches[0].clientX : e.clientX ;

    //store the last position of x 
    lastX.current = clientX;

  }

  const handlePointerUp = (e)=>{
    e.stopPropagation();
    e.preventDefault()
    setIsRotating(false);

     }

  const handlePointerMove = (e)=>{
    e.stopPropagation();
    e.preventDefault()

    if( isRotating){
        const clientX = e.touches ? e.touches[0].clientX : e.clientX ;

    //calculate the change in the horizontal position
    const delta = (clientX - lastX.current) / viewport.width;

    //update the island rotation based on the mouse
    islandRef.current.rotation.y += delta * 0.01 * Math.PI;

    //update the reference 
    lastX.current = clientX

    //update the rotation speed
    rotationSpeed.current = delta*0.01*Math.PI;
    }
    
  }

  const handleKeyDown = (e)=>{
    if (e.key === "ArrowLeft"){
        if(!isRotating) setIsRotating(true);
        islandRef.current.rotation.y += 0.01 * Math.PI;

    }
    else{
        if(!isRotating) setIsRotating(true);
        islandRef.current.rotation.y -= 0.01 * Math.PI;
    }
  }

  const handleKeyUp  = (e)=>{
    if (e.key === "ArrowLeft" || e.key === "ArrowRight"){
        setIsRotating(false);
    }
  }

  //useFrame is going to act on every single frame
  useFrame(()=>{
    if(! isRotating){
        rotationSpeed.current *= dampingFactor;  //to make the plane roll smoother

        //to completely stop the rotation if the speed is low
        if(Math.abs(rotationSpeed.current) <= 0.001){
            rotationSpeed.current = 0;
        }

        islandRef.current.rotation.y += rotationSpeed.current;
    }
    else{
        const rotation = islandRef.current.rotation.y;
 
    }

  })

  //to put all the events to action we will be using a hook called use frame - useframe comes from react three fiber directly
  React.useEffect(()=>{
         const canvas = gl.domElement;  //beacuse whenever we are touching the image/ 3d model we are not touching the regular dom instaed we are touching the canvas
        canvas.addEventListener("pointerdown",handlePointerDown);
        canvas.addEventListener("pointerup",handlePointerUp);
        canvas.addEventListener("pointermove",handlePointerMove);
        document.addEventListener("keydown",handleKeyDown);
        document.addEventListener("keyup",handleKeyUp);

    return ()=>{
        canvas.removeEventListener("pointerdown",handlePointerDown);
        canvas.removeEventListener("pointerup",handlePointerUp);
        canvas.removeEventListener("pointermove",handlePointerMove);
        document.removeEventListener("keydown",handleKeyDown);
        document.removeEventListener("keyup",handleKeyUp);
    }


  },[gl,handlePointerDown,handlePointerUp,handlePointerMove])

  
  return (
    // <a.group {...props} ref={islandRef}>
    //   <mesh
        
    //     geometry={nodes.polySurface944_tree_body_0.geometry}
    //     material={materials.PaletteMaterial001}
    //   />
    //   <mesh
    //     geometry={nodes.polySurface945_tree1_0.geometry}
    //     material={materials.PaletteMaterial001}
    //   />
    //   <mesh
        
    //     geometry={nodes.polySurface946_tree2_0.geometry}
    //     material={materials.PaletteMaterial001}
    //   />
    //   <mesh
        
    //     geometry={nodes.polySurface947_tree1_0.geometry}
    //     material={materials.PaletteMaterial001}
    //   />
    //   <mesh
        
    //     geometry={nodes.polySurface948_tree_body_0.geometry}
    //     material={materials.PaletteMaterial001}
    //   />
    //   <mesh
        
    //     geometry={nodes.polySurface949_tree_body_0.geometry}
    //     material={materials.PaletteMaterial001}
    //   />
    //   <mesh
        
    //     geometry={nodes.pCube11_rocks1_0.geometry}
    //     material={materials.PaletteMaterial001}
    //   />
    // </a.group>

    <a.group {...props} ref={islandRef}>
      <group position={[-7.738, 0, -87.926]} scale={1.127}>
        <mesh
          geometry={nodes.polySurface21_T_Atlas_0.geometry}
          material={materials.T_Atlas}
          position={[0, 107.134, 0]}
        />
      </group>
      <mesh
        geometry={nodes.polySurface119_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        
      />
      <group position={[355.839, 0, 0]}>
        <mesh
         
          
          geometry={nodes.polySurface32_T_Atlas_0.geometry}
          material={materials.T_Atlas}
          position={[0, 48.486, 0]}
        />
      </group>
      <group
        position={[-64.193, 208.51, -421.875]}
        scale={[0.324, 0.679, 0.324]}
      >
        <mesh
         
          
          geometry={nodes.pCylinder4_T_Atlas_0.geometry}
          material={materials.T_Atlas}
        />
        <mesh
         
          
          geometry={nodes.pCylinder4_lambert1_0.geometry}
          material={materials.lambert1}
        />
      </group>
      <group
        position={[111.861, 210.427, -124.833]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={[0.324, 0.679, 0.324]}
      >
        <mesh
         
          
          geometry={nodes.pCylinder5_T_Atlas_0.geometry}
          material={materials.T_Atlas}
        />
        <mesh
          geometry={nodes.pCylinder5_lambert1_0.geometry}
          material={materials.lambert1}
        />
      </group>
      <mesh
        geometry={nodes.polySurface2_T_Atlas_0.geometry}
        material={materials.T_Atlas}
      />
      <mesh
       
        
        geometry={nodes.polySurface3_T_Atlas_0.geometry}
        material={materials.T_Atlas}
      />
      <mesh
       
        
        geometry={nodes.polySurface4_T_Atlas_0.geometry}
        material={materials.T_Atlas}
      />
      <mesh
       
        
        geometry={nodes.polySurface5_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 48.486, 0]}
      />
      <mesh
       
        
        geometry={nodes.polySurface6_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 48.486, 0]}
      />
      <mesh
       
        
        geometry={nodes.polySurface7_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 48.486, 0]}
      />
      <mesh
       
        
        geometry={nodes.polySurface43_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 48.486, 0]}
      />
      <mesh
       
        
        geometry={nodes.pCube6_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[203.351, 123.243, -202.329]}
       
       
      />
      <mesh
       
        
        geometry={nodes.pCube8_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[-168.605, 161.096, 25.185]}
      />
      <mesh 
        geometry={nodes.pCube10_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[160.554, 50.634, 345.36]}
      />
      <mesh
        geometry={nodes.polySurface13_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[16.859, 29.763, -9.108]}
        scale={1.124}
      />
      <mesh
       
        
        geometry={nodes.pSphere1_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[344.509, 48.486, 120.497]}
      />
      <mesh
       
        
        geometry={nodes.polySurface37_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 48.486, 0]}
      />
      <mesh
       
        
        geometry={nodes.polySurface44_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 48.486, 0]}
      />
      <mesh
       
        
        geometry={nodes.polySurface45_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 48.486, 0]}
      />
      <mesh
       
        
        geometry={nodes.polySurface46_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 48.486, 0]}
      />
      <mesh
       
        
        geometry={nodes.polySurface47_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 48.486, 0]}
      />
      <mesh
       
        
        geometry={nodes.polySurface53_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 48.486, 0]}
      />
      <group position={[0, 19.571, 0]}>
        <mesh
         
          
          geometry={nodes.polySurface81_T_Atlas_0.geometry}
          material={materials.T_Atlas}
          position={[0, 28.914, 0]}
        />
      </group>
      <mesh
       
        
        geometry={nodes.polySurface77_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 48.486, 0]}
      />
      <mesh
       
        
        geometry={nodes.polySurface79_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 48.486, 0]}
      />
      <mesh
       
        
        geometry={nodes.polySurface80_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 48.486, 0]}
      />
      <mesh
       
        
        geometry={nodes.polySurface42_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 48.486, 0]}
      />
      <mesh
       
        
        geometry={nodes.polySurface49_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 48.486, 0]}
      />
      <mesh
       
        
        geometry={nodes.polySurface64_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 48.486, 0]}
      />
      <mesh
       
        
        geometry={nodes.polySurface75_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 48.486, 0]}
      />
      <mesh
       
        
        geometry={nodes.polySurface95_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[0, 28.914, 0]}
      />
      <mesh
       
        
        geometry={nodes.pCube25_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[160.221, 400.875, 396.048]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
       
        
        geometry={nodes.pCube28_T_Atlas_0.geometry}
        material={materials.T_Atlas}
      />
      <mesh
       
        
        geometry={nodes.pCylinder7_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[140.411, 126.255, -6.466]}
        scale={0.517}
      />
      <mesh
       
        
        geometry={nodes.pCylinder8_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[-4.447, 80.608, -315.619]}
      />
      <mesh
       
        
        geometry={nodes.polySurface98_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[-86.525, -9.993, -85.476]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
       
        
        geometry={nodes.pCube30_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[7.132, 0, 0]}
      />
      <mesh
       
        
        geometry={nodes.pPlane44_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[83.139, 136.653, -151.033]}
        rotation={[0, Math.PI / 3, 0]}
        scale={1.227}
      />
      <mesh
       
        
        geometry={nodes.pCylinder9_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[60.114, 130.156, -150.256]}
        scale={0.394}
      />
      <mesh
       
        
        geometry={nodes.pCylinder10_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[47.812, 130.156, -185.747]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={0.394}
      />
      <mesh
       
        
        geometry={nodes.pCylinder11_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[45.341, 130.156, -152.61]}
        rotation={[-1.391, -0.177, -0.769]}
        scale={0.305}
      />
      <mesh
       
        
        geometry={nodes.pCylinder12_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[53.08, 130.156, -198.319]}
        rotation={[-1.319, -0.009, -0.036]}
        scale={0.305}
      />
      <mesh
       
        
        geometry={nodes.pCylinder13_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[68.918, 128.938, -186.887]}
        rotation={[0, -0.873, 0]}
        scale={0.457}
      />
      <mesh
       
        
        geometry={nodes.pCylinder14_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[19.912, 130.156, -171.743]}
        rotation={[-1.347, 0.117, 0.476]}
        scale={0.305}
      />
      <mesh
       
        
        geometry={nodes.pCylinder15_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[21.181, 130.156, -150.678]}
        rotation={[-1.369, 0.152, 0.636]}
        scale={0.305}
      />
      <mesh
       
        
        geometry={nodes.pPlane47_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[163.181, -131.476, -282.33]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
       
        
        geometry={nodes.defaultBrush1Main_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[56.286, 39.202, 93.095]}
        rotation={[0, -0.074, 0]}
      />
      <mesh
       
        
        geometry={nodes.defaultBrush4Main_T_Atlas_0.geometry}
        material={materials.T_Atlas}
      />
      <mesh
       
        
        geometry={nodes.polySurface101_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[253.835, -83.96, 192.015]}
      />
      <mesh
       
        
        geometry={nodes.polySurface111_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[194.412, -176.753, 157.314]}
        rotation={[0.371, -0.008, 0.074]}
        scale={1.097}
      />
      <mesh
       
        
        geometry={nodes.polySurface112_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[-115.532, -210.173, 104.679]}
        rotation={[0, -1.336, 0]}
        scale={0.763}
      />
      <mesh
       
        
        geometry={nodes.polySurface113_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[-269.915, -146.133, -68.435]}
        rotation={[-Math.PI, 0.289, -Math.PI]}
        scale={0.574}
      />
      <mesh
       
        
        geometry={nodes.polySurface114_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[311.523, -200.986, 159.469]}
        rotation={[0.508, 0.66, -0.506]}
        scale={0.61}
      />
      <mesh
       
        
        geometry={nodes.polySurface115_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[-943.198, -236.752, 574.947]}
        rotation={[-Math.PI, -1.351, -Math.PI]}
        scale={1.012}
      />
      <mesh
       
        
        geometry={nodes.polySurface118_T_Atlas_0.geometry}
        material={materials.T_Atlas}
      />
      <mesh
       
        
        geometry={nodes.defaultBrush5Main_T_Atlas_0.geometry}
        material={materials.T_Atlas}
        position={[-297.559, -140.67, 363.676]}
        rotation={[0, -1.309, 0]}
      />
      <mesh
       
        
        geometry={nodes.pPlane48_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[139.173, 60.454, 284.835]}
        rotation={[0.252, -0.618, 0.419]}
        scale={1.056}
      />
      <mesh
       
        
        geometry={nodes.pPlane49_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[188.468, 75.95, 401.685]}
        rotation={[0.32, -0.879, 0.548]}
        scale={2.214}
      />
      <mesh
       
        
        geometry={nodes.pPlane50_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[98.07, 52.998, 239.2]}
        rotation={[0.248, 0.101, 0.185]}
        scale={0.356}
      />
      <mesh
       
        
        geometry={nodes.pPlane51_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[181.041, 53.626, 214.399]}
        rotation={[0.248, 0.101, 0.185]}
        scale={0.356}
      />
      <mesh
       
        
        geometry={nodes.pPlane52_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[253.92, 52.973, 228.24]}
        rotation={[0.291, 0.365, 0.091]}
        scale={1.056}
      />
      <mesh
       
        
        geometry={nodes.pPlane53_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[251.406, 52.657, 141.726]}
        rotation={[0.294, 0.378, 0.086]}
        scale={1.056}
      />
      <mesh
       
        
        geometry={nodes.pPlane54_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[206.906, 55.634, 143.271]}
        rotation={[0.624, 0.969, -0.335]}
        scale={0.49}
      />
      <mesh
       
        
        geometry={nodes.pPlane55_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[229.35, 52.381, 125.547]}
        rotation={[0.624, 0.969, -0.335]}
        scale={0.392}
      />
      <mesh
       
        
        geometry={nodes.pPlane56_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[232.539, 63.148, 168.647]}
        rotation={[0.436, -1.069, 0.707]}
        scale={1.056}
      />
      <mesh
       
        
        geometry={nodes.pPlane57_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[197.304, 61.36, 346.807]}
        rotation={[0.436, -1.069, 0.707]}
        scale={1.056}
      />
      <mesh
       
        
        geometry={nodes.pPlane58_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[341.531, 59.169, 138.98]}
        rotation={[0.32, 0.48, 0.042]}
        scale={1.445}
      />
      <mesh
       
        
        geometry={nodes.pPlane59_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[71.287, 55.03, 258.018]}
        rotation={[0.341, 0.545, 0.012]}
        scale={0.655}
      />
      <mesh
       
        
        geometry={nodes.pPlane60_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[-129.219, 73.709, 293.839]}
        rotation={[2.495, -0.927, 3.005]}
        scale={1.702}
      />
      <mesh
       
        
        geometry={nodes.pPlane61_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[11.385, 49.699, 192.272]}
        rotation={[1.691, 1.188, -1.466]}
        scale={1.506}
      />
      <mesh
       
        
        geometry={nodes.pPlane64_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[145.761, 0.188, 150.107]}
        rotation={[-0.071, -1.082, 0.033]}
        scale={0.656}
      />
      <mesh
       
        
        geometry={nodes.pPlane65_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[-43.574, 55.779, 240.596]}
        rotation={[-2.894, 1.451, 3.043]}
        scale={0.927}
      />
      <mesh
       
        
        geometry={nodes.pPlane66_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[-10.089, 51.976, 291.669]}
        rotation={[0.624, 0.969, -0.335]}
        scale={0.49}
      />
      <mesh
       
        
        geometry={nodes.pPlane67_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[68.229, 65.112, 270.818]}
        rotation={[0.723, -1.247, 1.036]}
        scale={0.796}
      />
      <mesh
       
        
        geometry={nodes.pPlane81_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[-568.888, -24.685, 33.072]}
        rotation={[-Math.PI, -0.634, -Math.PI]}
      />
      <mesh
       
        
        geometry={nodes.pPlane85_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[102.478, -11.6, -374.801]}
        rotation={[0, 1.042, 0]}
        scale={1.227}
      />
      <mesh
       
        
        geometry={nodes.pPlane86_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[-272.105, 64.63, 82.716]}
        rotation={[0.436, -1.069, 0.707]}
        scale={1.056}
      />
      <mesh
       
        
        geometry={nodes.pPlane87_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[-262.503, 58.905, -120.82]}
        rotation={[0.624, 0.969, -0.335]}
        scale={0.49}
      />
      <mesh
       
        
        geometry={nodes.pPlane88_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[-218.002, 55.927, -122.365]}
        rotation={[0.294, 0.378, 0.086]}
        scale={1.056}
      />
      <mesh
       
        
        geometry={nodes.pPlane93_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[-311.345, 0, 585.379]}
        rotation={[-Math.PI, -1.459, -Math.PI]}
      />
      <mesh
       
        
        geometry={nodes.pPlane100_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[443.901, -0.934, 119.583]}
        rotation={[0, 0.904, 0]}
      />
      <mesh
       
        
        geometry={nodes.pPlane103_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[-37.366, 0, -110.662]}
        rotation={[0, -0.372, 0]}
      />
      <mesh
       
        
        geometry={nodes.pPlane104_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[299.183, 53.657, -378.104]}
        rotation={[0.32, 0.48, 0.042]}
        scale={1.64}
      />
      <mesh
       
        
        geometry={nodes.pPlane105_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[136.942, -2.555, -619.118]}
        rotation={[0, 0.802, 0]}
        scale={0.786}
      />
      <mesh
       
        
        geometry={nodes.pPlane106_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[17.758, 34.577, -203.168]}
        rotation={[0.352, -0.305, 0.039]}
        scale={1.445}
      />
      <mesh
       
        
        geometry={nodes.pPlane107_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[22.153, 55.634, -282.297]}
        rotation={[0.624, 0.969, -0.335]}
        scale={0.49}
      />
      <mesh
       
        
        geometry={nodes.pPlane108_T_Leaves_0.geometry}
        material={materials.T_Leaves}
        position={[66.654, 52.657, -283.842]}
        rotation={[0.294, 0.378, 0.086]}
        scale={1.056}
      />
    </a.group>


  );
}

 
export default Island;

